version: 2
updates:
  - package-ecosystem: "poetry"
    cooldown:
      default-days: 7
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "src"
    labels:
      - "dependencies"
      - "python"
      - "src"

  - package-ecosystem: "poetry"
    cooldown:
      default-days: 7
    directory: "/layer"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "layer"
    labels:
      - "dependencies"
      - "python"
      - "layer"

  - package-ecosystem: "terraform"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "terraform"
    labels:
      - "dependencies"
      - "terraform"
